name = "EnhancedCSV"
uuid = "db2670d1-d57e-49e7-a9fb-f22487c808fe"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
DataPipes = "0.3"
JSON = "1.3.0"
StructArrays = "0.6, 0.7"
Tables = "1.12.1"
Unitful = "1.25.1"
YAML = "0.4.16"
julia = "1.10"
