name = "EnhancedCSV"
uuid = "db2670d1-d57e-49e7-a9fb-f22487c808fe"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataManipulation = "38052440-ad76-4236-8414-61389b2c5143"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
DataManipulation = "0.1.21"
YAML = "0.4.16"
julia = "1.10"
